tutorias/urls.py
from django.conf.urls.defaults import patterns,  url

urlpatterns = patterns('',
    url(r'^proceso_administrativo/$', 'tutorias.views.proceso_administrativo', name='proceso_administrativo'),
    url(r'^proceso_administrativo_proceso/$', 'tutorias.views.proceso_administrativo_proceso', name='proceso_administrativo_proceso'),
    url(r'^motivo/$', 'tutorias.views.motivo', name='motivo'),
    url(r'^servicio/$', 'tutorias.views.servicio', name='servicio'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^tutorias/', include('tutorias.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ventas/', include('ventas.urls')),
)

ventas/urls.py
from django.conf.urls.defaults import patterns,  url

urlpatterns = patterns('',
    url(r'^venta/$', 'ventas.views.venta', name='venta'),
)

tutorias/models.py
from django.db import models

from django.contrib.auth.models import User

class Url(models.Model):
	url = models.CharField(max_length=100)
	users = models.ManyToManyField(User, through='UserUrl')
	habilitada = models.BooleanField(default=True)

	def __unicode__(self):
		return self.url

class UserUrl(models.Model):
	url = models.ForeignKey(Url)
	user = models.ForeignKey(User)

ventas/models.py
from django.db import models

# Create your models here.

tutorias/forms.py
# -*- coding: utf-8 -*-

from django import forms


class ProcesoAdministrativoForm(forms.Form):
	
	PROCESO_CHOICES = (
        (None, '--------'),
        (u'Baja', u'Baja'),
        (u'Retención', u'Retención'),
        (u'Cambio de ciclo', u'Cambio de ciclo'),
        (u'Baja de materias', u'Baja de materias'),
        (u'Cancelación de venta', u'Cancelación de venta'),
        (u'Actualización de datos en Admisiones y/o materias de Aula virtual', u'Actualización de datos en Admisiones y/o materias de Aula virtual'),
        (u'Reducción o incremento de jornada', u'Reducción o incremento de jornada'),
        (u'Cambio de licenciatura', u'Cambio de licenciatura'),
        (u'Cambio de materias', u'Cambio de materias'),
    )
	matricula = forms.CharField(required=True)
	nombre_alumno = forms.CharField(required=True)
	email_alumno = forms.EmailField(required=True)
	proceso = forms.ChoiceField(required=True, choices=PROCESO_CHOICES)

ventas/forms.py
# -*- coding: utf-8 -*-
from django import forms

class VentaForm(forms.Form):
	SUPERVISORES = (
		(u'Heras Serrano José Antonio', u'Heras Serrano José Antonio'),
		(u'Hernández López María de Jesús', u'Hernández López María de Jesús'),
		(u'Mondragón Fragoso Luis Xavier', u'Mondragón Fragoso Luis Xavier'),
		(u'Olivares Barragán Francisco Javier', u'Olivares Barragán Francisco Javier'),
		(u'Otero Martín del Campo Rocío', u'Otero Martín del Campo Rocío'),
		(u'Ruiz Herrera Marlen', u'Ruiz Herrera Marlen'),
		(u'Sierra Juárez Dulce Damaris', u'Sierra Juárez Dulce Damaris'),
	)

	LICENCIATURAS = (
		(u'Administración',u'Administración'),
		(u'Administración de negocios',u'Administración de negocios'),
		(u'Administración de recursos humanos',u'Administración de recursos humanos'),
		(u'Administración y finanzas',u'Administración y finanzas'),
		(u'Administración de tecnologías de información',u'Administración de tecnologías de información'),
		(u'Contaduría pública',u'Contaduría pública'),
		(u'Contaduría y finanzas',u'Contaduría y finanzas'),
		(u'Ingeniería en sistemas computacionales',u'Ingeniería en sistemas computacionales'),
		(u'Ingeniería industrial',u'Ingeniería industrial'),
		(u'Ingeniería industrial y administración',u'Ingeniería industrial y administración'),
		(u'Mercadotecnia',u'Mercadotecnia'),
		(u'Negocios internacionales',u'Negocios internacionales'),
		(u'Pedagogía',u'Pedagogía'),
		(u'Psicología organizacional',u'Psicología organizacional'),
		(u'Comunicación',u'Comunicación'),
		(u'Comunicación Digital',u'Comunicación Digital'),
		(u'Comunicación Organizacional',u'Comunicación Organizacional'),
		(u'Derecho',u'Derecho'),
	)
	
	JORNADAS = (
		(u'Reducidas','r'),

	)

	nombre_alumno = forms.CharField(max_length=100, required=True)
	correo_alumno = forms.CharField(max_length=100, required=True)
	supervisor = forms.ChoiceField(required=True, choices=SUPERVISORES)
	deposito = forms.DecimalField(required=True)
	fecha_pago = forms.DateField(required=True)
	licenciatura = forms.ChoiceField(required=True, choices=LICENCIATURAS)
	jornada = forms.ChoiceField(required=True, choices=JORNADAS)
	ciclo_inicio = forms.DateField(required=True)
	tipo_ingreso = forms.ChoiceField(required=True)
	estatus = forms.ChoiceField(required=True)
	mes_venta = forms.ChoiceField(required=True)
	id_admisiones = forms.IntergerField(required=True)
	id_sugar = forms.IntergerField(required=True)
	observaciones = forms.TextField()

tutorias/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse
import mandrill
from django.template.loader import render_to_string
from django.conf import settings


def enviar_email(html, from_email, subject, to):
	info = {}
	info["html"] = html
	info["from_email"] = from_email
	info["subject"] = subject
	info["to"] = to
	enviar = mandrill.Mandrill(settings.API_KEY_MANDRILL).messages.send(message=info)
	if enviar[0]['status'] == 'sent' or enviar[0]['status'] == 'queued':
		return True
	return False

def proceso_administrativo(request):
	import collections
	if request.method == "POST":
		variables =  dict(request.POST.copy())
		del variables['csrfmiddlewaretoken']
		para_tabla = {}
		for variable,valor in variables.iteritems():
			valor = ", ".join(valor)
			para_tabla[variable] = variable.replace('_',' ').capitalize() +' : ' + valor
		content_table = ''
		para_tabla = collections.OrderedDict(sorted(para_tabla.items()))
		for c,v in para_tabla.iteritems():
			content_table += '<tr><td> %s </td></tr>' % v
		
		tabla = '<table border="1">%s</table>' % content_table
		
		from_email = "contacto@utel.edu.mx"
		subject = para_tabla['proceso']
		proceso = variables['proceso']
		if proceso == "Baja" or proceso == u'Retención':
			to = [{"email": "vcastito@utel.edu.mx", "type":"to", "name": "Ayuda UTEL"}]
		else:
		 	to = [{"email": "vcastito@utel.edu.mx", "type":"to", "name": "Escolares UTEL"}]
		html = render_to_string('tutorias/proceso.html', locals())
		if enviar_email(html, from_email, subject, to):
			return HttpResponse(u'Petición enviada')
		else:
			return HttpResponse(u'Petición fallida intentelo de nuevo')

	return render(request, 'tutorias/proceso_administrativo.html', locals())

import unicodedata
def elimina_tildes(s):
   return ''.join((c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn'))

def proceso_administrativo_proceso(request):
	proceso = elimina_tildes(request.GET['proceso']).lower().split(' ')[0]
	html  = "tutorias/%s.html" % proceso
	render_ =  render_to_string(html,{})
	return HttpResponse(render_)


def motivo(request):
	motivo = elimina_tildes(request.GET['motivo']).lower().split(' ')[0]
	html = render_to_string('motivos/%s.html' % motivo, {})
	return HttpResponse(html)

def servicio(request):
	servicio = elimina_tildes(request.GET['servicio']).lower().split(' ')[0]
	html =  render_to_string('servicios/%s.html' % servicio, {})
	return HttpResponse(html)

ventas/views.py
from django.shortcuts import render
from .forms import VentaForm

def venta(request):
	return render(request, "ventas/venta.html")

tutorias/templates/motivos/cambio.html
<select required name="motivo_de_cambio_de_universidad_o_sistema">
	<option value="No cumplió con sus expectativas">No cumplió con sus expectativas</option>
	<option value="No se acopló al estudio en línea">No se acopló al estudio en línea</option>
	<option value="Menor costo en otra universidad">Menor costo en otra universidad</option>
	<option value="Mayor equivalencia en otra universidad">Mayor equivalencia en otra universidad</option>
</select> <br><br>

 
 Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>
 

tutorias/templates/motivos/carga.html
<select required name="carga_de_trabajo">
	<option value="No tiene acceso a internet">No tiene acceso a internet</option>
	<option value="Amplia jornada">Amplia jornada</option>
	<option value="Por ascenso">Por ascenso</option>
	<option value="Nuevo trabajo">Nuevo trabajo</option>
</select> <br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/motivos/desempleo.html
Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/motivos/documentacion.html
<select name="documentacion" required multiple>
	<option value="Sin documentos entregados">Sin documentos entregados</option>
	<option value="Sin pago reflejado y/o comprobante">Sin pago reflejado y/o comprobante</option>
	<option value="Inscripción mal procesada">Inscripción mal procesada</option>
	<option value="Aun lo estaba pensando">Aun lo estaba pensando</option>
	<option value="Deposito para 'apartar' la beca">Deposito para "apartar" la beca</option>
	<option value="En espera de Equivalencias">En espera de Equivalencias</option>
</select><span>Manten presionado Ctrl para escoger más de uno</span>
<br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos * :
<br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/motivos/economicos.html
<select required name="motivo_economico">
	<option value="No puede solventar los gastos de la universidad">No puede solventar los gastos de la universidad</option>
	<option value="Pérdida de apoyo financiero (personal, familiar, empresa)">Pérdida de apoyo financiero (personal, familiar, empresa)</option>
	<option value="Adeudo con UTEL">Adeudo con UTEL</option>
</select> <br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos  * : 
<br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/motivos/institucional.html
<select required name="institucional_o_actividad">
	<option value="Se negó a dar documentación original">Se negó a dar documentación original</option>
	<option value="Falta de ingreso al aula virtual (inactividad)">Falta de ingreso al aula virtual (inactividad)</option>
	<option value="Nunca ingresó al aula virtual">Nunca ingresó al aula virtual</option>
	<option value="Documentos rechazados">Documentos rechazados</option>
	<option value="Documentos apócrifos">Documentos apócrifos</option>
</select> <br><br>

Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>
 
 
 
 
 
 
 
 
 
 
 
 

tutorias/templates/motivos/problemas.html
<select required name="problemas_de_salud">
	<option value="Accidente / Incapacidad">Accidente / Incapacidad</option>
	<option value="Hospitalización">Hospitalización</option>
	<option value="Enfermedad degenerativa">Enfermedad degenerativa</option>
	<option value="Embarazo">Embarazo</option>
</select> <br><br>

Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/motivos/servicio.html
¿Que área o departamento es responsable del mal servicio? *: <br><br>
<select id="mal_servicio" onchange="getServicio();" name="servicio_deficiente" required>
	<option value="" selected></option>
	<option value="Ventas">Ventas</option>
	<option value="Servicios escolares">Servicios escolares</option>
	<option value="Tesorería">Tesorería</option>
	<option value="Tutores">Tutores</option>
	<option value="Asesores">Asesores</option>
	<option value="Profesores">Profesores</option>
	<option value="Recursos educativos / Contenidos">Recursos educativos / Contenidos</option>
	<option value="Soporte técnico">Soporte técnico</option>
</select> <br><br>

<div id="step_servicio"></div>
 
 
 
 
 
 
 
 
 
 
 
 

tutorias/templates/servicios/asesores.html
Motivo: <br><br>
<select required name="tipo_de_servicio">
	<option value="Mal trato con alumno">Mal trato con alumno</option>
	<option value="Falta de seguimiento">Falta de seguimiento</option>
	<option value="Información incorrecta">Información incorrecta</option>
	<option value="Tiempo de respuesta">Tiempo de respuesta</option>
</select>
<br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/servicios/profesores.html
Motivo: <br><br>
<select required name="tipo_de_servicio">
	<option value="Mal trato con alumno">Mal trato con alumno</option>
	<option value="Falta de seguimiento">Falta de seguimiento</option>
	<option value="Información incorrecta">Información incorrecta</option>
	<option value="Tiempo de respuesta">Tiempo de respuesta</option>
</select>
<br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/servicios/recursos.html
Motivo: <br><br>
<select required name="tipo_de_servicio">
	<option value="Tiempo de respuesta">Tiempo de respuesta</option>
	<option value="Errores de contenido">Errores de contenido</option>
	<option value="Recurso no disponible">Recurso no disponible</option>
</select>
<br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/servicios/servicios.html
Motivo: <br><br>
<select required name="tipo_de_servicio">
	<option value="Asignación incorrecta de materias">Asignación incorrecta de materias</option>
	<option value="Sin seguimiento a equivalencia">Sin seguimiento a equivalencia</option>
	<option value="Asignación incorrecta de Licenciatura / Maestría / Educación continua">Asignación incorrecta de Licenciatura / Maestría / Educación continua</option>
	<option value="Error en ejecución de trámites">Error en ejecución de trámites</option>
	<option value="Tiempo de respuesta en trámites">Tiempo de respuesta en trámites</option>
</select><br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/servicios/soporte.html
Motivo: <br><br>
<select required name="tipo_de_servicio">
	<option value="Tiempo de respuesta">Tiempo de respuesta</option>
	<option value="Error en acceso a plataforma">Error en acceso a plataforma</option>
	<option value="Error en claves de acceso">Error en claves de acceso</option>
</select>
<br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/servicios/tesoreria.html
Motivo: <br><br>
<select required name="tipo_de_servicio">
	<option value="Adeudo incorrecto">Adeudo incorrecto</option>
	<option value="Tiempo de respuesta de requerimiento">Tiempo de respuesta de requerimiento</option>
	<option value="Mal trato con alumno">Mal trato con alumno</option>
	<option value="Tiempo de respuesta interno">Tiempo de respuesta interno</option>
	<option value="Rechazo apoyo  económico">Rechazo apoyo  económico</option>
	<option value="Incumplimiento de acuerdos">Incumplimiento de acuerdos</option>
	<option value="No se realiza convenio, o no le conviene al alumno">No se realiza convenio, o no le conviene al alumno</option>
</select><br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/servicios/tutores.html
Motivo: <br><br>
<select required name="tipo_de_servicio">
	<option value="Mal trato con alumno">Mal trato con alumno</option>
	<option value="Falta de seguimiento">Falta de seguimiento</option>
	<option value="Información incorrecta">Información incorrecta</option>
	<option value="Tiempo de respuesta">Tiempo de respuesta</option>
</select>
<br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/servicios/ventas.html
Motivo: <br><br>
<select required name="tipo_de_servicio">
	<option value="Falta de información">Falta de información</option>
	<option value="Información incorrecta">Información incorrecta</option>
	<option value="Venta ingresada en periodo incorrecto o no solicitado">Venta ingresada en periodo incorrecto o no solicitado</option>
	<option value="Incumplimiento de acuerdos">Incumplimiento de acuerdos</option>
</select><br><br>
Ingresa todos los comentarios necesarios pero breves y objetivos  * : <br><br> <textarea required name="observaciones" cols="30" rows="10"></textarea>

tutorias/templates/tutorias/baja.html
<h1>Sección para bajas</h1> <br><br>

Tipo de baja *: <br><br>
<select name="tipo_de_baja" id="tipo_baja">
	<option value="definitiva">Definitiva</option>
	<option value="temporal"> Temporal</option>
</select> <br><br>

Primer fecha cuando el alumno la solicitó *: <br><br>
<input type="date" name="fecha_de_solicitud" required> <br><br>
	

Ciclo de ingreso *: <br><br>
<select required name="ciclo_de_ingreso">
	<option value="Septiembre 2011 (AA012 Regular)">Septiembre 2011 (AA012 Regular)</option>
	<option value="Noviembre 2011 (AB012 Anticipada)">Noviembre 2011 (AB012 Anticipada)</option>
	<option value="Enero 2012 (AB012 Regular)">Enero 2012 (AB012 Regular)</option>
	<option value="Marzo 2012 (AC012 Anticipada)">Marzo 2012 (AC012 Anticipada)</option>
	<option value="Mayo 2012 (AC012 Regular)">Mayo 2012 (AC012 Regular)</option>
	<option value="Julio 2012 (AA012 Anticipada)">Julio 2012 (AA012 Anticipada)</option>
	<option value="Septiembre 2012 (AA013 Regular)">Septiembre 2012 (AA013 Regular)</option>
	<option value="Noviembre 2012 (AB013 Anticipada)">Noviembre 2012 (AB013 Anticipada)</option>
	<option value="Enero 2013 (AB013 Regular)">Enero 2013 (AB013 Regular)</option>
	<option value="Marzo 2013 (AC013 Anticipada)">Marzo 2013 (AC013 Anticipada)</option>
	<option value="Mayo 2013 (AC013 Regular)">Mayo 2013 (AC013 Regular)</option>
	<option value="Julio 2013 (AA014 Anticipada)">Julio 2013 (AA014 Anticipada)</option>
	<option value="Septiembre 2013 (AA014 Regular)">Septiembre 2013 (AA014 Regular)</option>
	<option value="Noviembre 2013 (AB014 Anticipada)">Noviembre 2013 (AB014 Anticipada)</option>
	<option value="Enero 2014 (AB014 Regular)">Enero 2014 (AB014 Regular)</option>
	<option value="Marzo 2014 (AC014 Anticipada)">Marzo 2014 (AC014 Anticipada)</option>
	<option value="Mayo 2014 (AC014 Regular)">Mayo 2014 (AC014 Regular)</option>
	<option value="Julio 2014 (AA015 Anticipada)">Julio 2014 (AA015 Anticipada)</option>
	<option value="Septiembre 2014 (AA015 Regular)">Septiembre 2014 (AA015 Regular)</option>
	<option value="ECD2013081">ECD2013081</option>
	<option value="ECD2014011">ECD2014011</option>
	<option value="ECD2014061">ECD2014061</option>
	<option value="ECC2014021">ECC2014021</option>
	<option value="ECC2014022">ECC2014022</option>
	<option value="ECC2014051">ECC2014051</option>
	<option value="ECC2014081">ECC2014081</option>
	<option value="ECC2014082">ECC2014082</option>
	<option value="ECC2014101">ECC2014101</option>
	<option value="ECC2014102">ECC2014102</option>
</select>
<br><br>

Indica la carrera o modalidad *: <br><br>

<select required name="carrera">
	<option value="LADGE101 Administración">LADGE101 Administración</option>
	<option value="LADNE101 Administración de Negocios">LADNE101 Administración de Negocios</option>
	<option value="LADTI101 Administración de Tecnologías de &nbsp;Información">LADTI101 Administración de Tecnologías de &nbsp;Información</option>
	<option value="LADRH101 Administración en Recursos Humanos">LADRH101 Administración en Recursos Humanos</option>
	<option value="LADFI101 Administración y Finanzas">LADFI101 Administración y Finanzas</option>
	<option value="LCCGE101 Comunicación">LCCGE101 Comunicación</option>
	<option value="LCCD101 Comunicación Digital">LCCD101 Comunicación Digital</option>
	<option value="LCCOR101 Comunicación Organizacional">LCCOR101 Comunicación Organizacional</option>
	<option value="LCPGE101 Contaduría Pública">LCPGE101 Contaduría Pública</option>
	<option value="LCPFI101 Contaduría y Finanzas">LCPFI101 Contaduría y Finanzas</option>
	<option value="LDEGE101 Derecho">LDEGE101 Derecho</option>
	<option value="LDEEM101 Derecho Empresarial">LDEEM101 Derecho Empresarial</option>
	<option value="LDEIN101 Derecho Internacional">LDEIN101 Derecho Internacional</option>
	<option value="LISGE101 Ingeniería en Sistemas Computacionales">LISGE101 Ingeniería en Sistemas Computacionales</option>
	<option value="LIIGE101 Ingeniería Industrial">LIIGE101 Ingeniería Industrial</option>
	<option value="LIIAD101 Ingeniería Industrial y Administración">LIIAD101 Ingeniería Industrial y Administración</option>
	<option value="LMEGE101 Mercadotecnía">LMEGE101 Mercadotecnía</option>
	<option value="LNIGE101 Negocios Internacionales">LNIGE101 Negocios Internacionales</option>
	<option value="LPEGE101 Pedagogía">LPEGE101 Pedagogía</option>
	<option value="LPSOR101 Psicología Organizacional">LPSOR101 Psicología Organizacional</option>
	<option value="Educación continua">Educación continua</option>
	<option value="Maestría en Administración">Maestría en Administración</option>
	<option value="Maestría en educación">Maestría en educación</option>
	<option value="Global English">Global English</option>
</select> <br><br>

Tipo de jornada (Si no aplica seleccionar N/A) *: <br><br>

<select required name="tipo_de_jornada">
	<option value="N/A">N/A</option>
	<option value="Reducida">Reducida</option>
	<option value="Completa">Completa</option>
	<option value="Intensiva">Intensiva</option>
</select> <br><br>

Edad del alumno *: <br><br>

<input type="number" required name="edad"> <br><br>

Género *: <br><br>

<select required>
	<option value="Masculino">Masculino</option>
	<option value="Femenino">Femenino</option>
</select> <br><br>


Estado civil *: <br><br>

<select required name="estado_civil">
	<option value="Soltero">Soltero</option>
	<option value="Casado">Casado</option>
	<option value="Unión libre">Unión libre</option>
</select> <br><br>


País y ciudad de residencia* : <br><br>
<input type="text" required name="residencia"> <br><br>

Porcentaje o descuento de beca *: <br><br>
<input type="text" required name="descuento_de_beca"> <br><br>


Estado actual en admisiones *: <br><br>

<select required name="estado_en_admisiones">
	<option value="Matriculado">Matriculado</option>
	<option value="Baja Temporal">Baja Temporal</option>
	<option value="Baja definitiva">Baja definitiva</option>
	<option value="Inactivo">Inactivo</option>
	<option value="Pendiente de baja">Pendiente de baja</option>
</select> <br><br>


Motivo de la baja * : <br><br>

<select id="motivos" name="motivo_de_baja"  onchange="changeMotivos();" required >
	<option value=""></option>
	<option value="Económicos">Económicos</option>
	<option value="Desempleo">Desempleo</option>
	<option value="Cambio de universidad o sistema">Cambio de universidad o sistema</option>
	<option value="Problemas de salud">Problemas de salud</option>
	<option value="Carga de trabajo">Carga de trabajo</option>
	<option value="Servicio deficiente del área">Servicio deficiente del área</option>
	<option value="Institucional o actividad">Institucional o actividad</option>
	<option value="Documentación (uso exclusivo de control escolar)">Documentación (uso exclusivo de control escolar)</option>
</select> <br><br>

<div id="step_2">

</div>

tutorias/templates/tutorias/proceso.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
</head>
<body>
	<div>
		{{tabla|safe}}
	</div>
</body>
</html>

tutorias/templates/tutorias/proceso_administrativo.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<script src="{{STATIC_URL}}js/jquery.js"></script>
	<script>

		function changeMotivos(){
			$('#step_2').html("");
			if($('#motivos').val() != ""){
				$.get('/tutorias/motivo/', {'motivo':$('#motivos').val()}, function(data) {
					$('#step_2').append(data);
				});
			}
		}

		function getServicio(){
			$('#step_servicio').html("");
			if($('#mal_servicio').val() != ""){
				$.get('/tutorias/servicio/',{'servicio': $('#mal_servicio').val()}, function(data) {
					$('#step_servicio').html(data);
				});
			}
		}

		function textFieldOtro(div_text_id, id_text, opcion){
			var val = $('#'+opcion).val();
			if(val == "Otro"){
				$('#'+div_text_id).show();
				$('#'+id_text).attr('required', 'required');
			}else{
				$('#'+div_text_id).hide();
				$('#'+id_text).removeAttr('required');
			}
		}
		$(document).ready(function($) {
			$('#id_proceso').on('change',function(event){
				$.get('/tutorias/proceso_administrativo_proceso/', {'proceso': $('#id_proceso').val()},  function(data) {
					$('#step_1').html(data);
				});
			});
		});
	</script>
</head>
<body>
	<form action="/tutorias/proceso_administrativo/" method="POST">
		{%csrf_token%}
		Matriucla *: <br><br>
		<input type="text"  name="matricula" required><br><br>
		Nombre Alumno *: <br><br>
		<input type="text" name="alumno" required><br><br>
		Email Alumno *: <br><br>
		<input type="email" name="email" required><br><br>
		Proceso *: <br><br>
		<select name="proceso" id="id_proceso" required>
			<option value="">--------</option>
			<option value="Baja">Baja</option>
			<option value="Retención">Retención</option>
			<option value="Cambio de ciclo">Cambio de ciclo</option>
			<option value="Baja de materias">Baja de materias</option>
			<option value="Cancelación de venta">Cancelación de venta</option>
			<option value="Actualización de datos en Admisiones y/o materias de Aula virtual">Actualización de datos en Admisiones y/o materias de Aula virtual</option>
			<option value="Reducción o incremento de jornada">Reducción o incremento de jornada</option>
			<option value="Cambio de licenciatura">Cambio de licenciatura</option>
			<option value="Cambio de materias">Cambio de materias</option>
		</select>

		
		<div id="step_1">
			
		</div>
		<input type="submit">
	</form>
</body>
</html>